### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by yaobo-lab** [api7/kong-to-apisix#1]
可以将kong 的数据迁到 apisix 的意思吗？可以写详细些。步骤什么的。谢谢

**Comment by Yiyiyimu** [comment]
Hi @yaobo-lab We are still working on this project and right now it's still a bit far from the expected. And yes, that's the purpose of this project, trying to provide a tool to migrate from kong to apisix without pain.

I'll ping you when we provide a minimal working product~

**Comment by yaobo-lab** [comment]
> Hi @yaobo-lab We are still working on this project and right now it's still a bit far from the expected. And yes, that's the purpose of this project, trying to provide a tool to migrate from kong to apisix without pain.
> 
> I'll ping you when we provide a minimal working product~

ok
